export const UFList = [
  { label: "Acre", id: "AC" },
  { label: "Alagoas", id: "AL" },
  { label: "Amap\u00e1", id: "AP" },
  { label: "Amazonas", id: "AM" },
  { label: "Bahia", id: "BA" },
  { label: "Cear\u00e1", id: "CE" },
  { label: "Distrito Federal", id: "DF" },
  { label: "Esp\u00edrito Santo", id: "ES" },
  { label: "Goi\u00e1s", id: "GO" },
  { label: "Maranh\u00e3o", id: "MA" },
  { label: "Mato Grosso", id: "MT" },
  { label: "Mato Grosso do Sul", id: "MS" },
  { label: "Minas Gerais", id: "MG" },
  { label: "Paran\u00e1", id: "PR" },
  { label: "Para\u00edba", id: "PB" },
  { label: "Par\u00e1", id: "PA" },
  { label: "Pernambuco", id: "PE" },
  { label: "Piau\u00ed", id: "PI" },
  { label: "Rio Grande do Norte", id: "RN" },
  { label: "Rio Grande do Sul", id: "RS" },
  { label: "Rio de Janeiro", id: "RJ" },
  { label: "Rond\u00f4nia", id: "RO" },
  { label: "Roraima", id: "RR" },
  { label: "Santa Catarina", id: "SC" },
  { label: "Sergipe", id: "SE" },
  { label: "S\u00e3o Paulo", id: "SP" },
  { label: "Tocantins", id: "TO" },
];
